# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Deploy to website VM

on:
  release:
    types: [published]

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Deploy
      uses: appleboy/ssh-action@master
      env:
        NODE_ENV: ${{ secrets.WEBSITE_NODE_ENV }}
        DB_HOST: ${{ secrets.WEBSITE_DB_HOST }}
        DB_DATABASE: ${{ secrets.WEBSITE_DB_DATABASE }}
        DB_USER: ${{ secrets.WEBSITE_DB_USER }}
        DB_PASSWORD: ${{ secrets.WEBSITE_DB_PASSWORD }}
        DB_PORT: ${{ secrets.WEBSITE_DB_PORT }}
        COOKIE_SECRET: ${{ secrets.WEBSITE_COOKIE_SECRET }}
        SESSION_SECRET: ${{ secrets.WEBSITE_SESSION_SECRET }}
        JWT_SECRET: ${{ secrets.WEBSITE_JWT_SECRET }}
        RECAPTCHA_SECRET: ${{ secrets.WEBSITE_RECAPTCCHA_SECRET }}
      with:
        host: ${{ secrets.WEBSITE_HOST }}
        username: ${{ secrets.WEBSITE_USERNAME }}
        key: ${{ secrets.WEBSITE_PRIVATEKEY }}
        port: ${{ secrets.WEBSITE_PORT }}
        passphrase: ${{ secrets.WEBSITE_PASSPHRASE }}
        envs: NODE_ENV,DB_HOST,DB_DATABASE,DB_USER,DB_PASSWORD,DB_PORT,COOKIE_SECRET,JWT_SECRET,RECAPTCHA_SECRET
        script: |
          cd ~/website
          forever stop bin/www
          cd ~
          rm -rf old
          mkdir old
          mv website ~/old
          mkdir website
          cd ~/website
          git init
          git pull git@github.com:Aurinsk/website.git
          npm install
          touch .env
          echo 'NODE_ENV=$NODE_ENV' >> .env
          echo 'DB_HOST=$DB_HOST' >> .env
          echo 'DB_DATABASE=$DB_DATABASE' >> .env
          echo 'DB_USER=$DB_USER' >> .env
          echo 'DB_PASSWORD=$DB_PASSWORD' >> .env
          echo 'DB_PORT=$DB_PORT' >> .env
          echo 'COOKIE_SECRET=$COOKIE_SECRET' >> .env
          echo 'SESSION_SECRET=$SESSION_SECRET' >> .env
          echo 'JWT_SECRET=$JWT_SECRET' >> .env
          echo 'RECAPTCHA_SECRET=$RECAPTCHA_SECRET' >> .env
          forever start bin/www
